replicaCount: 1

image:
  repository: dockerhub-username/spa-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: spa.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

extraEnvVars: []

resources: {}
