apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spa.fullname" . }}
  labels:
    {{ include "spa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "spa.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "spa.labels" . | nindent 8 }}
    spec:
      containers:
        - name: spa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- range .Values.extraEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
